services:
  payment:
    build: .
    container_name: payment
    environment:
      - SERVER_PORT=8383
    ports:
      - "8383:8383"
    networks:
      - reactive-ms-network

networks:
  reactive-ms-network:
    external: true